### PR TITLE
vokoscreen OOMs my system (+fix)

### PR DESCRIPTION
**Pull request by alexander255**
Currently vokoscreen will unconditionally store all in-progress video material onto `/tmp/vokoscreen-${USER}`. Since that is often times a RAM-partition on many systems (including mine), this behavior will eventually consume all system memory, grinding the system to a halt – not very pleasant. Also this means that if all data has been recorded in one go it will still have to be copied across partitions (even if it doesn't need to be merged).

This patch fixes this by:

  * Making `vokoscreen` safe for any file path as storage locations (currently a single space in the path means death, for instance)
  * Changing the location of the temporary directory to being a subdirectory of the currently selected target directory

### CODE REVIEW

**Comment by vkohaupt** [comment]
Hallo Alexander,

thanks for the greatfull patch, without Audio very good, with Alsa very 
good, but i see one error with Pulse, the Executing command as all 
detectet Mikrofons and a record fails.

This is ok:
[vokoscreen] Executing command: "/usr/bin/ffmpeg"
("-report", "-f", "x11grab", "-draw_mouse", "1", "-framerate", "25", 
"-video_size", "1920x1080", "-i", ":0+0,0",

This...
"-name", "vokoscreen", "-i", 
"alsa_output.pci-0000_00_1b.0.analog-stereo.monitor",

... and this fails a record
"-name", "vokoscreen", "-i", "alsa_input.pci-0000_00_1b.0.analog-stereo",

This is my seleted device in pulse and is ok:
"-f", "pulse", "-name", "vokoscreen", "-i", 
"alsa_input.usb-046d_0809_A6307261-02.analog-mono",

This is ok:
"-pix_fmt", "yuv420p", "-c:v", "libx264", "-preset", "veryfast", "-c:a", 
"libmp3lame", "-q:v", "1", "-s", "1920x1080", "-f", "matroska", 
"/home/vk/Videos/.vokoscreen-recording/vokoscreen-2017-04-11_22-18-11.mkv")

Please test with Pulse and fix the error and make a new diff

**Comment by alexander255** [comment]
Fixed!

There was an `if` with some misleading indentation (goto fail 😁) that caused this. Thanks to `gcc`'s warnings this was easy to find. Some warnings of this kind (probably around for a long time) still remain through…

I don't want to complain or anything but the argument list patch of mine probably barely scratched the surface on the amount of refactoring that the main `screencast.cpp` definitely needs. I suppose this was one of your very first GUI programming projects 🙂?

Also the license header is weird:

> This program is free software; you can redistribute it and/or modify
> it under the terms of the GNU General Public License as published by
> the Free Software Foundation; **either version 2 of the License.**
> [Nothing]

Beste Screencapturing-Software für Linux jedenfalls! :+1:

**Comment by vkohaupt** [comment]
Alexander Schlarb schrieb am 12.04.2017 um 00:17:

> I don't want to complain or anything but the argument list patch of mine probably barely scratched the surface on the amount of refactoring that the main `screencast.cpp` definitely needs. I suppose this was one of your very first GUI programming projects 🙂?

Jetzt habe ich aber ein Problem was die Argumentlisten angeht, für mich 
und meine Tester ist es unabdingbar das man schnell den kompletten 
Befehl, der im Terminal ausgegeben wird, per copy und paste verarbeiten 
kann, was über die Ausgabe von QStringlist so nicht mehr geht.

Ich stell mir das dann in etwa so vor.

QString arguments_1 = ffmpegProgram;
for (int i=0; i<arguments.count(); i++)
{
   arguments_1 = arguments_1 + " " + arguments[ i ];
}
qDebug() << "[vokoscreen]"<< "Executing command:" << arguments_1;
qDebug( " " );

werde in den nächsten Tagen weiter testen und wenn mir nichts weiter 
auffällt übernehmen.

**Comment by alexander255** [comment]
Das ist mir beim Debuggen in der Tat auch aufgefallen. So was wie du vorgeschlagen hast hatte ich auch zuerst drinnen (nur eben mit `.join(' ')`), aber dann wurde alles falsch gequotet – geht also leider nicht.

Habe das jetzt mit einer Unterfunktion und einer Schleife die jeden Parameter einzeln an `QDebug` übergibt gelöst. Sollte jetzt passen. :slightly_smiling_face:

**Comment by vkohaupt** [comment]
Hallo Alexander,
habs nun eingebaut und das nun im Videoordner temporär zwischengespeichert wird ist um Welten besser als im tmp.
Großartige Arbeit vielen Dank.

**Pull request closed without merging**
